//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace davaleba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Categories
    {
        public int Id { get; set; }
        public int CategoriesId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
    }
}
